# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f71ea77e10b3b9ec42424b1d2e7ed1fcbcf928480ceb095b1a76bf86af7b2ee7013366d4c6c600931f5329e184a40d85649cce5d726a9791e7748bd1b984c88

test:
  secret_key_base: 9176c98ab6cb6c7bb3988ba096df252055faaf8d64bc6fb87419b27044ddcd98fa184fab93a8cfb273774e11c481c92fc3e71f7bec16e5608f7ced4fbf127e7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
